### ISSUE TITLE
Adaptive for small population of host?

### ISSUE THREAD

**Issue by yjiakang** [blekhmanlab/hominid#3]
Hello! Thanks for building such a wonderful pipeline for identifying associations between host SNPs and host microbiome. I am new in this field. I have a basic but important question about this. 
  From the examples in your article, I notice that the host population is very large for accurate results. Suppose I only have three plants: one cultivar named A, one cultivar named B, and their progeny named C. Additionally, their genomes and  microbiomes are known. Would it be possible to associate the host SNPs and their taxa? Any reply would be appreciated. Thanks in advance.

**Comment by BlekhmanLabMember** [comment]
Three samples is way too few for an association study.  There is a minimum of 50 samples to run HOMINID.
